### ISSUE TITLE
Minor change to Biopython SeqIO example

### ISSUE THREAD

**Issue by peterjc** [MichielStock/Teaching#1]
In `Scientific_python/Skimage_biopython.ipynb` rather than:

```
from Bio import SeqIO
for item in SeqIO.FastaIO.FastaIterator(open('data/sweet_taste_receptor.txt', 'r')):
    print(item)
```

our documentation would use:

```
from Bio import SeqIO
for item in SeqIO.parse('data/sweet_taste_receptor.txt', 'fasta'):
    print(item)
```

(I'd actually use double quotes - your examples are inconsistent on this point)

Key points: Emphasises file-format neutral API (makes switching file format later much easier, closer to the usage you followed for `AlignIO`) and also will take care of closing the file handle internally.

**Comment by MichielStock** [comment]
Hi Peter,

Thanks for your suggestion. Just using the `parse` function in `SeqIO` is more general and thus more didactic. 

I also made the quotation consistent throughout the examples.

Cheers,

Michiel
